{% set version = "2.0.8" %}

package:
  name: wgrib2
  version: {{ version }}

source:
  fn: wgrib2_nolib.tgz
  url: ftp://ftp.cpc.ncep.noaa.gov/wd51we/wgrib2/wgrib2_nolib.tgz.v{{ version }}
  sha256: 860b97f1f768da10386c41a635ed4951bd9c496ab402ccea1b48d4871dbffb04
  patches:
    - no_proj.patch

build:
  number: 0
  skip: True  # [win or osx]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - g2clib
    - mysql-connector-c 6.1.*
    - libnetcdf
    - libpng
    - zlib
    - jasper
  run:
    - g2clib
    - mysql-connector-c 6.1.*
    - libnetcdf
    - libpng
    - zlib
    - jasper

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    # - wgrib2 -config # works but the return code !=0

about:
  home: http://www.cpc.ncep.noaa.gov/products/wesley/wgrib2
  license: GPL-2.0
  license_file: wgrib2/LICENSE-wgrib2
  summary: 'Utility to read and write grib2 files'

extra:
  recipe-maintainers:
    - ocefpaf
