{% set version = "3.1.2" %}

package:
  name: wgrib2
  version: {{ version }}

source:
  fn: wgrib2_nolib.tgz
  url: https://ftp.cpc.ncep.noaa.gov/wd51we/wgrib2/wgrib2_nolib.tgz.v{{ version }}
  sha256: 548c77cf3cf9b8cddcebcb3cebcfbddbe93bb4a429d7a833efb030cd5ca121d2
  patches:
    - no_proj.patch
    - jasper4.patch

build:
  number: 4
  skip: true  # [win or osx]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  host:
    - g2clib
    - mysql-devel
    - libaec
    - libnetcdf
    - libpng
    - zlib
    - jasper
  run:
    - g2clib
    - mysql-libs
    - libaec
    - libnetcdf
    - libpng
    - zlib
    - jasper

test:
  commands:
    # - wgrib2 -config # works but the return code !=0

about:
  home: http://www.cpc.ncep.noaa.gov/products/wesley/wgrib2
  license: GPL-2.0-only
  license_file: wgrib2/LICENSE-wgrib2
  summary: Utility to read and write grib2 files

extra:
  recipe-maintainers:
    - zklaus
    - ocefpaf
    - akrherz
